fix: yml file

diff --git a/.github/workflows/pr-title-check.yml b/.github/workflows/pr-title-check.yml
--- a/.github/workflows/pr-title-check.yml
+++ b/.github/workflows/pr-title-check.yml
@@ -19,7 +19,6 @@ jobs:
           if [[ ! "$PR_TITLE" =~ ^CSN-[0-9]{3,5} ]]; then
             echo "Invalid title: $PR_TITLE"
             echo "::set-output name=invalid::true"
-            exit 1 # This will fail the job
           else
             echo "Valid title"
             echo "::set-output name=invalid::false"
@@ -68,3 +67,8 @@ jobs:
                 body: commentBody
               })
             }
+      - name: Fail the check for invalid title
+        if: steps.check_title.outputs.invalid == 'true'
+        run: |
+          echo "Exiting with failure due to invalid PR title"
+          exit 1
